# Week 4

# Policy -- The Bihar Kosi Recovery Project

## Summary

Kosi River is a trans-boundary river -- upper steam flowing along Nepal all the way down to lower course in the Bihar region in India (ref). It subjected to repeated flooding, especially during the Summer Monsoon season from June to September. The most notable and disastrous flood was in 2008 -- as known as the 2008 Kosi Flooding. The 2008 Kosi Flooding was originated from the breach of upstream embankment, channel discharge then rapidly displaced to downstream of Kosi, in the North Bihar regions (Ref). 6 districts in the North Bihar was inundated; 5.5 million people became homeless; more than 2500 km2 of cultivated land was submerged; economic loss of US\$18.7 million was also reported (ref). Since then, the Indian government started the Bihar Kosi Flood Recovery Project to revitalise the Northern Bihar and enhance its flood resilience capacity.

It is important to note that Kosi River is a dynamic river as it has shifted westward for at least 113 m to the current location due to active tectonic movements (ref). Its dynamic nature created numerous abandoned channel that increases the risks of flooding to surrounding area, by providing more flood water outlets through the abandoned paleochannels (ref). Therefore, it is equally important to understand its physical settings while progressing on socio-economic reconstructions.

The project objectives of the "Environment and Social Management Framework" are listed as follow:

1.  Reconstruction of houses that are earthquake and flood resistant
2.  Enhancing connectivity by building and repairing roads and bridges
3.  Strengthening flood management capacity in Kosi Basin
4.  Building social and financial capital by expanding livelihoods opportunities
